2024 storing credentials
ArjanCodes/examples pull request #33
Opened 2023-12-13 13:59 UTC by ABDreos

2023-12-13 15:46 UTC, egges requested changes

2023-12-13 15:46 UTC, egges commented on 2024/storing_credentials/main.py
> +                "content": "You are a assistant to arjancodes, skilled in software design patterns with creative flair. And likes to end your sentences with an swedish joke",
Great change :)

2023-12-13 15:46 UTC, egges commented on 2024/storing_credentials/README.md
I use dashes instead of underscore in the other folder names. Can you change this to storing-credentials for consistency?

2023-12-14 09:44 UTC, ABDreos commented on 2024/storing_credentials/main.py
> +                "content": "You are a assistant to arjancodes, skilled in software design patterns with creative flair. And likes to end your sentences with an swedish joke",
:D

2024-01-09 13:52 UTC, closed without merging